CREATE OR REPLACE TABLE DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.STG_LEADS AS
SELECT DISTINCT
    LEAD_ID,
    TO_DATE(CONCAT('20', RIGHT(FORM_SUBMISSION_DATE, 8)), 'YYYY-MM-DD') AS FORM_SUBMISSION_DATE,
    SALES_CALL_COUNT,
    SALES_TEXT_COUNT,
    SALES_EMAIL_COUNT,
    FIRST_SALES_CALL_DATE,
    FIRST_TEXT_SENT_DATE,
    FIRST_MEETING_BOOKED_DATE,
    LAST_SALES_CALL_DATE,
    LAST_SALES_ACTIVITY_DATE,
    LAST_SALES_EMAIL_DATE,

    TRY_TO_DOUBLE(REPLACE(PREDICTED_SALES_WITH_OWNER, ',', '.')) AS PREDICTED_SALES_WITH_OWNER,

    DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA_UTIL.CLEAN_STR_ARRAY(MARKETPLACES_USED)   AS MARKETPLACES_USED,
    DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA_UTIL.CLEAN_STR_ARRAY(ONLINE_ORDERING_USED) AS ONLINE_ORDERING_USED,
    DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA_UTIL.CLEAN_STR_ARRAY(CUISINE_TYPES)        AS CUISINE_TYPES,

    TRY_TO_NUMBER(LOCATION_COUNT) AS LOCATION_COUNT,

    CONNECTED_WITH_DECISION_MAKER,
    STATUS,
    CONVERTED_OPPORTUNITY_ID
FROM DEMO_DB.GTM_CASE.LEADS;



