create or replace transient table DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.FACT_LEAD as
select
  LEAD_ID,
  FORM_SUBMISSION_TS::date   as FORM_SUBMISSION_DATE,
  STATUS,
  CONNECTED_WITH_DM,
  LOCATION_COUNT,
  PREDICTED_SALES_WITH_OWNER,
  CONVERTED_OPPORTUNITY_ID
from DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.STG2_LEADS;
