create or replace transient table DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.FACT_GTM_SPEND as
select
  MONTH_DATE,
  ADVERTISING,
  OUTBOUND_COMP,
  INBOUND_COMP,
  TOTAL_SPEND
from DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.STG2_SPEND;
