create or replace view DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.MART_H1_WINS_BY_SOURCE as
select
  d.CHANNEL_GROUP,
  o.SOURCE_CHANNEL,
  count(*) as WINS
from DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.FACT_OPPORTUNITY o
left join DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.DIM_CHANNEL d
  on o.SOURCE_CHANNEL = d.CHANNEL_KEY
where o.STAGE_NAME = 'CLOSED WON'
  and o.CLOSE_DATE between $h1_start and $h1_end
group by 1,2
order by WINS desc;
