create or replace view DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.MART_H1_LOSS_REASONS as
select
  r.REASON_GROUP,
  o.LOSS_REASON_GROUP,
  count(*) as CLOSED_LOST
from DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.FACT_OPPORTUNITY o
left join DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.DIM_REASON r
  on o.LOSS_REASON_GROUP = r.REASON_GROUP
where o.STAGE_NAME like 'CLOSED LOST%'
  and o.CLOSE_DATE between $h1_start and $h1_end
group by 1,2
order by CLOSED_LOST desc;
