CREATE OR REPLACE TABLE DEMO_DB.DE_CASE_BILALQURESHI0309_SCHEMA.STG_OPPORTUNITIES AS
SELECT distinct
    OPPORTUNITY_ID,
    STAGE_NAME,
    LOST_REASON_C,
    CLOSED_LOST_NOTES_C,
    BUSINESS_ISSUE_C,
    HOW_DID_YOU_HEAR_ABOUT_US_C,
    CREATED_DATE,
    DEMO_HELD,
        TO_DATE(
        CONCAT('20', RIGHT(demo_set_date, 8)),
        'YYYY-MM-DD'
    ) as DEMO_SET_DATE,
    DEMO_TIME,
        TO_DATE(
        CONCAT('20', RIGHT(close_date, 8)),
        'YYYY-MM-DD'
    ) as CLOSE_DATE,
    LAST_SALES_CALL_DATE_TIME,
    ACCOUNT_ID
FROM DEMO_DB.GTM_CASE.OPPORTUNITIES;


